### ISSUE TITLE
database management

### ISSUE THREAD

**Issue by ghost** [abantecart/docker#2]
Hi team. This more of suggestion than an issue, if you add phpmyadmin users will have browser access to the db https://hub.docker.com/r/phpmyadmin/phpmyadmin/ 
Thanks a lot

**Comment by vdvpie22** [comment]
You can add phpmyadmin in docker-compose.yml as new service. I'm not sure everyone needs it, for example, I use Workbench

**Comment by abantecart** [comment]
I agree that this might be a matter of preference. Perhaps, we can add this as an options
