### ISSUE TITLE
Needs to be updated - PHP etc are no longer new enough

### ISSUE THREAD

**Issue by WGandy** [abantecart/docker#3]
Installing this 'as-is' in May 2022 gave me errors about the PHP version. Updating the PHP to a newer version (in the Docker file) gave me an issue with `E: Package 'mysql-client' has no installation candidate`

**Comment by vdvpie22** [comment]
Try last version. Working with 1.3.3 version. 
Abantecart v.2.0 still not working. We will update in future.
